### ISSUE TITLE
Datasets from bioRxiv paper

### ISSUE THREAD

**Issue by mw55309** [ythuang0522/homopolish#16]
Hello

Are the polished genomes available to download from the homopolish paper? https://www.biorxiv.org/content/10.1101/2020.09.19.304949v1.full.pdf

Thanks
M

**Comment by ythuang0522** [comment]
Hi Mick, 

The R9.4/R10.3 Zymo genomes polished by Medaka+Homopolish can be found in the [data](https://github.com/ythuang0522/homopolish/tree/master/data) folder: R9.4_medaka+homopolish.tar.gz and R10.3_medaka+homopolish.tar.gz vs reference (truth.tar.gz). median Q scores were computed by [fastmer](https://github.com/jts/assembly_accuracy/blob/master/fastmer.py).
