### ISSUE TITLE
nothing (seems to be) happening

### ISSUE THREAD

**Issue by JWDebler** [ythuang0522/homopolish#24]
Hi, 

I am running the command like this:

`python3 /home/ubuntu/homopolish/homopolish.py polish -a genome.fasta  -s /home/ubuntu/homopolish/fungi.msh -m /home/ubuntu/homopolish/R9.4.pkl -o homopolish`

And all I am getting is this for all contigs:
```
[2021/03/30 06:03] INFO: Stage: Select closely-related genomes
TIME Select closely-related genomes: 0 MINS 0 SECS.
This contig tig00000048 closely-related genome is less than 5, not to polish...
TIME Total: 0 MINS 10 SECS.
```
It doesn't seem like anything is actually happening, but I still get an output fasta file. 
Can you tell me what this means?

Cheers.

**Comment by ythuang0522** [comment]
This means it can’t find closely related genomes from ncbi. Looks Like you are polishing a fungal genome. There are two possibilities. One is your fungal genome is a novel species very distant from those available in NCBI. The power of polishing by homologs would diminish. The other is, if your fungal assembly is too fragmented, the short contigs would failed species identification by mash.

**Comment by JWDebler** [comment]
That is it then, there are only a handful of related species on NCBI. Thanks.
