### ISSUE TITLE
db_path not defined

### ISSUE THREAD

**Issue by hxg2760** [ythuang0522/homopolish#34]
Hi, 

Just a quick report - This is directly from the latest github copy ( 28/05/2021).  Commands used below . No issues when using the bacteria.msh sketch option. So might be specific issue when we are not using the sketch and opted to use genus straight away. 

python3 ~/Bioapp/homopolish/homopolish.py polish -m ~/Bioapp/homopolish/R9.4.pkl -a assembly.racon.medaka.fasta -g Pasteurella --download_contig_nums 10

/media/gs/SSD_1TB/Nanopore_Data/GN035.hac/UMP_Pasteru_out/output/debug
[M::mm_idx_gen::0.075*1.01] collected minimizers
[M::mm_idx_gen::0.105*1.01] sorted minimizers
[M::main::0.105*1.01] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.111*1.01] mid_occ = 100
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.116*1.01] distinct minimizers: 228812 (99.37% are singletons); average occurrences: 1.018; average spacing: 9.991
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -cx asm5 --cs=long -t 1 /media/gs/SSD_1TB/Nanopore_Data/GN035.hac/UMP_Pasteru_out/output/debug/contig_1/contig_1.fasta /media/gs/SSD_1TB/Nanopore_Data/GN035.hac/UMP_Pasteru_out/output/debug/homologous/All_homologous_sequences.fna.gz
[M::main] Real time: 0.121 sec; CPU: 0.122 sec; Peak RSS: 0.020 GB
0.15107154846191406
Traceback (most recent call last):
  File "/home/gs/Bioapp/homopolish/homopolish.py", line 58, in <module>
    main()
  File "/home/gs/Bioapp/homopolish/homopolish.py", line 42, in main
    FLAGS.output_dir, FLAGS.minimap_args, FLAGS.mash_threshold, FLAGS.download_contig_nums, FLAGS.debug, FLAGS.meta, FLAGS.local_DB_path)
  File "/home/gs/Bioapp/homopolish/modules/polish_interface.py", line 324, in polish_genome
    out = genus_species_polish(out, assembly_name, output_dir_debug,mash_screen, assembly, model_path, sketch_path, genus_species, threads, output_dir, minimap_args, mash_threshold, download_contig_nums, debug, meta)
  File "/home/gs/Bioapp/homopolish/modules/polish_interface.py", line 238, in genus_species_polish
    out.append(check_homopolish(paf, contig_name, contig_output_dir, contig, minimap_args, threads, db_path, model_path))
NameError: name 'db_path' is not defined

Regards, 
Gan

**Comment by ythuang0522** [comment]
Thanks. We have pushed a fixed version (0.2.3).
