### ISSUE TITLE
Let user set number of cpu and output path of middle file in modpolish

### ISSUE THREAD

**Issue by chen1i6c04** [ythuang0522/homopolish#45]
Hi 

I tried the new feature `modpolish`, it's amazing.
But I couldn't set number of cpu  and output path of middle file.
If I can set the arguments by myself, it will be easier to use.

Thanks

**Comment by ythuang0522** [comment]
Hi @chen1i6c04 , you can specify the CPU counts via `-t` and output path via `-o` in the latest committed version on GitHub.

**Comment by chen1i6c04** [comment]
Thanks your update
