### ISSUE TITLE
Alternatives to Evaluating Assembly Quality without Reads

### ISSUE THREAD

**Issue by afvrbanac** [ythuang0522/homopolish#46]
Hello, I have R10.4 nanopore data (Bifidobacteria isolate genomes) that I assembled with trycycler (using Flye, miniasm+minipolish, raven), polished with Medaka, and then polished with Homopolish. They are all closed, single main contigs with some strains containing plasmids.

I noticed that methods to evaluate assembly quality that use the raw reads (i.e Inspector) report much worse assembly quality after using Homopolish. I assume this is because the reads no longer map well to the assembly in areas that Homopolish has corrected. Are there alternative evaluation tools that are recommended to use with assemblies processed by Homopolish besides CheckM? I unfortunately do not have reference genomes for my strains as they are novel isolates so there is no way for me to evaluate quality in that manner.

**Comment by ythuang0522** [comment]
Hi @afvrbanac, I am a bit skeptical of the inspector which used read consensus for evaluation. The real issue of ONT is systematic errors, in which the basecalling algorithm consistently miscalled at the same locus for all reads. Homopolish was designed for solving this obstacle by looking at indel conservation in homologs, which will against the read consensus. 
<img width="339" alt="image" src="https://user-images.githubusercontent.com/6086073/170163077-09705916-ff77-485b-8ab8-592b1d541730.png">

Without a reference, the completeness of core genes is also the way we did for reference-free evaluation (i.e., CheckM/Busco/Ideel). Unfortunately, they are not sensitive enough to reflect the accuracy when passing Q40, and I believed all your genomes should be close to Q50 (we had a recent test using Illumina showing 
consistent Q50 on R9.4 after Homopolish). In our experience, this is good enough for most studies. Hence, I would suggest you just continue with the downstream analysis. When any important mutation related to your study is found, you can always double confirm by IGV later. I hope this helps.

**Comment by afvrbanac** [comment]
Awesome, this is very helpful--thank you! Really appreciate the graphic and extra info.
