### ISSUE TITLE
Bacterial sketches file not found?

### ISSUE THREAD

**Issue by vebaev** [ythuang0522/homopolish#59]
I tried to download the sketches files, new and old, but url is not found?

Its good to have backup of the datasets like in Zenodo...

**Comment by ythuang0522** [comment]
Hi @vebaev, The DNS was changed by the network admin and we don't know why yet. We are contacting them to change it back. In the meantime, please use the direct IP address instead.

http://140.123.104.107/bioinfo/mash_sketches/bacteria.msh.gz

Sorry for the inconvenience.

Yao-Ting
