### ISSUE TITLE
virus, bacteria, and fungi sketches link not working

### ISSUE THREAD

**Issue by jpanibe** [ythuang0522/homopolish#65]
Please post the updated links of the sketches so I can download them. They are not working.

**Comment by liaoyoyo** [comment]
Hi @jpanibe 

The updated links for the sketches can be found at the following location:
https://bioinfo.cs.ccu.edu.tw/bioinfo/downloads/Homopolish_Sketch/

Here you will find the following files available for download:
- bacteria.msh.gz
- fungi.msh.gz
- virus.msh.gz
- bacteria_old_20220819.msh.gz
- plasmids.msh.gz

You can also check this page for additional information:
http://bioinfo.cs.ccu.edu.tw/bioinfo/download.html

Let me know if you encounter any issues!

Best regards, 
liaoyoyo2001
